#!/bin/bash
#Menu

echo -e "------------ Selamat datang di server $MYIP -----------"
echo -e "Silakan ketik daftar perintah yang tersedia"
echo -e "========================DAFTAR MENU==========================="
echo -e "Apa yang ingin anda lakukan?"
echo -e "1)  Menampilkan daftar perintah yang tersedia	= menu"
echo -e "2)  Membuat akun SSH	= usernew"
echo -e "3)  Membuat akun trial	= trial"
echo -e "4)  Menghapus akun SSH	= hapus"
echo -e "5)  Cek user login	= login"
echo -e "6)  Cek member SSH	= member"
echo -e "7)  Restart service dropbear,squid3,dll	= restart"
echo -e "8)  Reboot VPS	= reboot"
echo -e "9)  Speedtest VPS	= speedtest"
echo -e "10) Cek Kualitas VPS	= bench-network"
echo -e "11) Cek RAM VPS	= ps-mem"
echo -e "12) informasi = about"
echo -e "13)  Penpanjang Masa Aktif	= renew"
echo -e "14)  Hapus akun Expired = delete"
echo -e "=========================Boost SSH============================"
echo -e "ALL SUPPORTED by "
echo -e "FB	: "
echo -e "WhatsApp	: "
echo -e "Website	: "
echo -e "Website	: "

echo -e ""
